# Generated by Django 4.2.13 on 2025-05-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
        ('accounts', '0002_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti_badge_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mbti_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='mbti.personalitytype'),
        ),
    ]
