# Generated by Django 4.2.13 on 2025-05-21 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(help_text='상품 제공 금융사', max_length=50)),
                ('product_type', models.CharField(choices=[('deposit', '예금'), ('saving', '적금'), ('fund', '펀드'), ('stock', '주식'), ('etf', 'ETF'), ('pension', '연금'), ('insurance', '보험'), ('loan', '대출')], max_length=20)),
                ('risk_level', models.CharField(choices=[('very_low', '매우 낮음'), ('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('very_high', '매우 높음')], max_length=20)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('api_source', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('type_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('risk_preference', models.CharField(help_text='안정형(S)/도전형(R)', max_length=20)),
                ('consumption_style', models.CharField(help_text='계획형(P)/즉흥형(I)', max_length=20)),
                ('goal_orientation', models.CharField(help_text='장기형(M)/단기형(D)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('consumption', '소비 습관'), ('investment', '투자 습관'), ('risk', '위험 선호도'), ('analysis', '정보 탐색/분석'), ('goal', '목표/동기')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mbti.survey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('kakaotalk', 'KakaoTalk')], max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, help_text='추천 우선순위 (낮은 숫자가 높은 우선순위)')),
                ('reason', models.TextField(blank=True)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('personality_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='mbti.personalitytype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbti.financialproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='characters/')),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('personality_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='mbti.personalitytype')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbti.surveyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
