# Generated by Django 4.2.13 on 2025-05-23 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_depositproduct_fin_prdt_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=10, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('homp_url', models.URLField(blank=True, null=True)),
                ('cal_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('dcls_chrg_man', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_cd', models.CharField(max_length=2)),
                ('area_nm', models.CharField(max_length=20)),
                ('exis_yn', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='savings.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='AnnuityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('avg_prft_rate', models.FloatField()),
                ('prdt_type_nm', models.CharField(max_length=50)),
                ('sale_strt_day', models.DateField()),
                ('fin_co', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.financialcompany')),
            ],
        ),
    ]
