# Generated by Django 4.2.13 on 2025-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_financialcompany_companybranch_annuityproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='mtrt_int',
            field=models.FloatField(default=0.0, verbose_name='만기 이자율'),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='save_trm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='저축 기간(개월)'),
        ),
    ]
