# Generated by Django 4.2.13 on 2025-05-21 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mbti', '0001_initial'),
        ('boards', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('general', '일반 토론'), ('investment', '투자 정보'), ('mbti_type', 'MBTI 유형별 토론'), ('recommendation', '상품 추천/후기')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='related_mbti_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_boards', to='mbti.personalitytype'),
        ),
        migrations.AddField(
            model_name='board',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
