# Generated by Django 4.2.13 on 2025-05-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_board_options_board_category_board_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
